<?php

/**
 * @package ActiveRecord
 */

namespace ActiveRecord\Adapters;

use ActiveRecord\Json;
use ActiveRecord\Uuid;
use ActiveRecord\Column;
use ActiveRecord\Inflector;
use ActiveRecord\Connection;
use ActiveRecord\Adapters\Clickhouse\HttpClient;
use ActiveRecord\Adapters\Clickhouse\Statement;
use ActiveRecord\Exceptions\DatabaseException;

/**
 * Adapter for ClickHouse 25.9 or later, over its HTTP interface.
 *
 * Built for analytics (OLAP). Inserts are synchronous by default: the fastest
 * for each save() and errors are reported. Each one writes a data part, though,
 * so for many small inserts from many clients (event tracking, say) use a
 * connection with async_insert=1, which batches them on the server and still
 * waits for the write. Model::insert_all() is the fastest of all. Any
 * ClickHouse setting can be changed per connection in the connection URL:
 *
 * <code>
 * clickhouse://user:pass@host:8123/database
 * clickhouse://user:pass@host:8443/database?secure=1&compress=0
 * clickhouse://user:pass@host/database?async_insert=0&max_execution_time=30
 * </code>
 *
 * Connection options (the rest of the query string are settings):
 *
 * <ul>
 * <li><b>secure:</b> 1 for HTTPS (default port 8443 instead of 8123)</li>
 * <li><b>compress:</b> 0 to turn off compressed responses (default on)</li>
 * <li><b>connect_timeout:</b> seconds to wait for the connection (default 10)</li>
 * <li><b>timeout:</b> seconds a whole request may take (default no limit)</li>
 * </ul>
 *
 * There are no transactions and no auto-increment. A primary key column named
 * id, or declared with the model's $primary_key, of type UInt128 (or Int128,
 * UInt256, Int256, UUID, String) gets a UUIDv7 generated in PHP on insert; see
 * {@link Uuid}. Columns of the table's ORDER BY are not taken as primary key:
 * they are not unique. UPDATE needs the table to be created with
 * SETTINGS enable_block_number_column = 1, enable_block_offset_column = 1.
 *
 * @package ActiveRecord
 */
class ClickhouseAdapter extends Connection
{
    public static $DEFAULT_PORT = 8123;

    public static $INSERT_BATCH_SIZE = 100000;

    /**
     * With async_insert=1, INSERT statements with at least this many rows skip
     * the async insert buffer: batched by the client already, they are written
     * faster straight away (about 50 ms against 250 ms for 100000 rows). 0
     * turns this off.
     *
     * @var int
     */
    public static $SYNC_INSERT_MIN_ROWS = 1000;

    /**
     * Settings sent with every query unless the connection URL sets them.
     *
     * - async_insert: off. A synchronous insert answers in about 2 ms, against
     *   50 to 200 ms for an async one waiting for the buffer to be flushed.
     *   Each one writes a data part that merges have to clean up, which is fine
     *   at a few inserts per second per table; at hundreds, ClickHouse first
     *   delays and then rejects inserts ("too many parts"), so turn
     *   async_insert on for that load.
     * - wait_for_async_insert: on, for when async_insert is turned on. As
     *   ClickHouse recommends: with 0 an insert that fails is lost without an
     *   error, and a client writing faster than the server can take gets no
     *   backpressure.
     * - lightweight_deletes_sync: do not wait for a DELETE to finish.
     * - output_format_json_quote_64bit_integers: keep the numbers inside JSON
     *   columns as numbers.
     *
     * @var array
     */
    public static $DEFAULT_SETTINGS = [
        'async_insert' => 0,
        'wait_for_async_insert' => 1,
        'lightweight_deletes_sync' => 0,
        'output_format_json_quote_64bit_integers' => 0,
    ];

    /**
     * Sequence names returned by get_sequence_name(): the UUIDv7 of a new
     * record as a decimal (integer key) or as UUID text (UUID or String key).
     */
    const UUIDV7_DECIMAL = 'uuidv7';
    const UUIDV7_TEXT = 'uuidv7-text';

    /**
     * @var array Settings for every query of this connection
     */
    private $settings;

    /**
     * @var string|null The key generated by the last next_sequence_value()
     */
    private $last_id;

    /**
     * @var string
     */
    private $server_version;

    protected function __construct($info)
    {
        $options = $info->options ?? [];
        $secure = !empty($options['secure']);
        $port = $info->port ?? ($secure ? 8443 : static::$DEFAULT_PORT);
        $url = ($secure ? 'https' : 'http') . "://{$info->host}:$port/";

        $this->connection = new HttpClient(
            $url,
            $info->user ?? 'default',
            $info->pass ?? '',
            $info->db,
            ($options['compress'] ?? '1') != '0',
            (int)($options['connect_timeout'] ?? 10),
            (int)($options['timeout'] ?? 0)
        );

        unset($options['secure'], $options['compress'], $options['connect_timeout'], $options['timeout']);
        $this->settings = $options + static::$DEFAULT_SETTINGS;

        // Connecting is lazy over HTTP: ask for something so that a wrong host,
        // user or database fails here, as it does with PDO
        $this->server_version = $this->query_and_fetch_one('SELECT version()');
    }

    /**
     * @return string Such as 25.9.7.56
     */
    public function server_version()
    {
        return $this->server_version;
    }

    /**
     * Runs a query. Values are bound client-side: each ? outside quotes and
     * comments is replaced by the value as a ClickHouse literal.
     *
     * @param string $sql
     * @param array &$values Positional bind values
     * @return Statement
     */
    public function query($sql, &$values = [])
    {
        $this->log_query($sql, $values);
        $this->last_query = $sql;

        if ($values) {
            $sql = $this->interpolate($sql, $values);
        }

        // ClickHouse requires a WHERE on DELETE, even to delete every row
        if (preg_match('/^\s*DELETE\s+FROM\s+(?:`[^`]*`|[^\s`])+\s*$/i', $sql)) {
            $sql .= ' WHERE 1';
        }

        return $this->execute($sql);
    }

    /**
     * Writes the rows as literals straight into the INSERT, skipping the bind
     * markers: faster for the large batches of Model::insert_all().
     */
    public function insert_rows($table, array $columns, array $rows, $sequence = null)
    {
        $names = array_map([$this, 'quote_name'], $columns);

        if ($sequence) {
            $names[] = $this->quote_name($sequence[0]);
        }

        $tuples = [];

        foreach ($rows as $row) {
            $literals = [];

            foreach ($row as $value) {
                $literals[] = $this->literal($value);
            }

            if ($sequence) {
                $literals[] = $this->next_sequence_value($sequence[1]);
            }

            $tuples[] = '(' . implode(',', $literals) . ')';
        }

        $head = "INSERT INTO $table (" . implode(',', $names) . ') VALUES ';

        // the statement can be megabytes long: log and remember only its head
        $this->last_query = $head . '... (' . count($rows) . ' rows)';
        $this->log_query($this->last_query);

        $settings = [];
        if (static::$SYNC_INSERT_MIN_ROWS > 0 && count($rows) >= static::$SYNC_INSERT_MIN_ROWS) {
            $settings['async_insert'] = 0;
        }

        return $this->execute($head . implode(',', $tuples), $settings);
    }

    /**
     * Quotes a string as a ClickHouse literal.
     *
     * @param string $string
     * @return string
     */
    public function escape($string)
    {
        return $this->literal((string)$string);
    }

    /**
     * Turns a PHP value into a ClickHouse literal. Strings are always quoted,
     * numeric ones too: ClickHouse converts them to the column's type, and an
     * unquoted integer beyond Int64 would be read as a lossy Float64.
     *
     * @param mixed $value
     * @return string
     */
    public function literal($value)
    {
        if (is_string($value)) {
            return "'" . strtr($value, ['\\' => '\\\\', "'" => "\\'"]) . "'";
        }

        if (is_int($value)) {
            return (string)$value;
        }

        if (is_null($value)) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        if (is_float($value)) {
            if (is_nan($value)) {
                return 'nan';
            }

            return is_infinite($value) ? ($value > 0 ? 'inf' : '-inf') : var_export($value, true);
        }

        if (is_array($value)) {
            if (array_is_list($value)) {
                return '[' . implode(',', array_map([$this, 'literal'], $value)) . ']';
            }

            // a hash is a Map
            $pairs = [];
            foreach ($value as $key => $item) {
                $pairs[] = $this->literal($key) . ':' . $this->literal($item);
            }

            return '{' . implode(',', $pairs) . '}';
        }

        if ($value instanceof \DateTimeInterface) {
            return "'" . $this->datetime_to_string($value) . "'";
        }

        if ($value instanceof Json) {
            return $this->literal($value->to_json());
        }

        return $this->literal((string)$value);
    }

    /**
     * Writes a DateTime as its Unix timestamp. ClickHouse reads a string of
     * digits as one in any DateTime or DateTime64 column, whatever its time
     * zone, so the instant is kept exactly. Wall-clock text would be read in
     * the column's or the server's time zone, and before 26.2 INSERT and
     * UPDATE did not even agree on which one when session_timezone was set.
     * Sub-second precision is dropped, as with the other adapters.
     *
     * @param \DateTimeInterface $datetime
     * @return string
     */
    public function datetime_to_string($datetime)
    {
        return (string)$datetime->getTimestamp();
    }

    /**
     * The generated key of the last insert, when the model's key is generated.
     */
    public function insert_id($sequence = null)
    {
        return $this->last_id;
    }

    public function supports_sequences()
    {
        return true;
    }

    /**
     * Keys are generated only for column types that can hold a UUIDv7.
     */
    public function get_sequence_name($table, $column_name, $column = null)
    {
        if (!$column) {
            return null;
        }

        if (in_array($column->raw_type, ['uint128', 'int128', 'uint256', 'int256'])) {
            return self::UUIDV7_DECIMAL;
        }

        if (in_array($column->raw_type, ['uuid', 'string'])) {
            return self::UUIDV7_TEXT;
        }

        return null;
    }

    /**
     * Generates the key in PHP and returns it as a literal. It is remembered
     * for insert_id().
     */
    public function next_sequence_value($sequence_name)
    {
        $this->last_id = Uuid::v7();

        if ($sequence_name === self::UUIDV7_TEXT) {
            $this->last_id = Uuid::to_string($this->last_id);
        }

        return "'{$this->last_id}'";
    }

    public function limit($sql, $offset, $limit)
    {
        $offset = is_null($offset) ? '' : intval($offset) . ',';
        $limit = intval($limit);
        return "$sql LIMIT {$offset}$limit";
    }

    /**
     * Columns come from system.columns. MATERIALIZED and ALIAS columns are left
     * out: SELECT * does not return them and INSERT rejects them.
     *
     * @param string $table Possibly quoted and database-qualified
     */
    public function query_column_info($table)
    {
        $parts = explode('.', str_replace('`', '', $table));
        $name = array_pop($parts);
        $database = array_pop($parts);

        $sql = 'SELECT name, type, default_kind, default_expression FROM system.columns'
            . ' WHERE database = ' . ($database === null ? 'currentDatabase()' : '?') . ' AND table = ?'
            . " AND default_kind NOT IN ('MATERIALIZED', 'ALIAS') ORDER BY position";
        $values = $database === null ? [$name] : [$database, $name];

        return $this->query($sql, $values);
    }

    public function columns($table)
    {
        $columns = parent::columns($table);

        if (!$columns) {
            throw new DatabaseException("Table $table does not exist", 60);
        }

        return $columns;
    }

    public function query_for_tables()
    {
        return $this->query('SHOW TABLES');
    }

    public function create_column(&$column)
    {
        $c = new Column();
        $c->inflected_name = Inflector::instance()->variablize($column['name']);
        $c->name = $column['name'];
        $c->nullable = false;
        $c->auto_increment = false;
        // only by convention: the sorting key says nothing about uniqueness
        $c->pk = $column['name'] === 'id';

        $type = $column['type'];

        while (preg_match('/^(Nullable|LowCardinality)\((.*)\)$/', $type, $matches)) {
            $c->nullable = $c->nullable || $matches[1] === 'Nullable';
            $type = $matches[2];
        }

        preg_match('/^(\w+)(?:\((.*)\))?$/s', $type, $matches);
        $c->raw_type = strtolower($matches[1] ?? $type);
        $arguments = $matches[2] ?? '';

        if (preg_match('/^u?int(8|16|32|64|128|256)$|^bool$/', $c->raw_type)) {
            $c->type = Column::INTEGER;
        } elseif (preg_match('/^float|^decimal/', $c->raw_type)) {
            $c->type = Column::DECIMAL;
            $c->length = $c->raw_type == 'decimal' ? intval($arguments) : null;
        } elseif (in_array($c->raw_type, ['date', 'date32'])) {
            $c->type = Column::DATE;
            $c->length = 10;
        } elseif (in_array($c->raw_type, ['datetime', 'datetime64'])) {
            $c->type = Column::DATETIME;
            $c->length = 19;
        } elseif (in_array($c->raw_type, ['json', 'object'])) {
            $c->type = Column::JSON;
        } elseif (in_array($c->raw_type, ['array', 'map', 'tuple', 'nested'])) {
            // no Column type fits: values are PHP arrays, read and written as they are
            $c->type = null;
        } else {
            $c->type = Column::STRING;
            $c->length = $c->raw_type == 'fixedstring' ? intval($arguments) : null;
        }

        if ($column['default_kind'] === 'DEFAULT') {
            $c->default = $c->cast_default(static::default_value($column['default_expression']), $this);
        }

        return $c;
    }

    /**
     * The value of a literal DEFAULT expression. Anything computed, like now(),
     * is left to the server: the model starts with null and does not send it.
     */
    private static function default_value($expression)
    {
        if (preg_match("/^'((?:[^'\\\\]|\\\\.)*)'$/s", $expression, $matches)) {
            return strtr($matches[1], Statement::UNESCAPE);
        }

        if (is_numeric($expression)) {
            return $expression;
        }

        return ['true' => 1, 'false' => 0][$expression] ?? null;
    }

    /**
     * ClickHouse speaks UTF-8 only: there is nothing to set.
     */
    public function set_encoding($charset)
    {
    }

    public function transaction()
    {
        throw new DatabaseException('ClickHouse does not support transactions');
    }

    public function commit()
    {
        throw new DatabaseException('ClickHouse does not support transactions');
    }

    public function rollback()
    {
        throw new DatabaseException('ClickHouse does not support transactions');
    }

    /**
     * Bind markers do not apply: values are written into the SQL.
     */
    public function max_bind_parameters()
    {
        return PHP_INT_MAX;
    }

    public function native_database_types()
    {
        return [
            'primary_key' => 'UInt128',
            'string' => ['name' => 'String'],
            'text' => ['name' => 'String'],
            'integer' => ['name' => 'Int32'],
            'float' => ['name' => 'Float64'],
            'decimal' => ['name' => 'Decimal', 'length' => 18],
            'datetime' => ['name' => 'DateTime'],
            'timestamp' => ['name' => 'DateTime'],
            'time' => ['name' => 'String'],
            'date' => ['name' => 'Date'],
            'binary' => ['name' => 'String'],
            'boolean' => ['name' => 'Bool']
        ];
    }

    /**
     * @param string $sql Final query text
     * @param array $settings Settings for this query only, over the connection's
     * @return Statement
     */
    private function execute($sql, array $settings = [])
    {
        $settings += $this->settings;
        $settings['default_format'] = 'TabSeparatedWithNamesAndTypes';

        $response = $this->connection->execute($sql, $settings);

        return new Statement($response['body'], $response['format'], $response['summary'], $response['timezone']);
    }

    /**
     * Replaces each ? outside string literals, quoted identifiers and comments
     * with the next value as a literal.
     */
    private function interpolate($sql, array $values)
    {
        $values = array_values($values);
        $count = count($values);
        $index = 0;

        $sql = preg_replace_callback(
            '/\'(?:[^\'\\\\]|\\\\.)*+\'|"(?:[^"\\\\]|\\\\.)*+"|`(?:[^`\\\\]|\\\\.)*+`|--[^\n]*+|\/\*.*?\*\/|\?/s',
            function ($matches) use ($values, $count, &$index) {
                if ($matches[0] !== '?') {
                    return $matches[0];
                }

                if ($index >= $count) {
                    throw new DatabaseException("No bound parameter for index $index");
                }

                return $this->literal($values[$index++]);
            },
            $sql
        );

        if ($index < $count) {
            throw new DatabaseException("$count values bound but only $index parameters in the query");
        }

        return $sql;
    }
}
